homepage/urls.py
from django.urls import path
from .views import index

app_name = 'homepage'

urlpatterns = [
    path('', index, name='index'),
]

payment/urls.py
from django.urls import path
from .views import checkout, invoice, useCoupon

app_name = 'payment'

urlpatterns = [
    path('<int:id>', checkout, name="checkout"),
    path('invoice/<int:id>', invoice, name="invoice"),
    path('useCoupon', useCoupon, name="useCoupon"),
]

products/urls.py
from django.urls import path
from .views import products, product_byid, addToCart, tambahKurangCart, grabTotal
from django.conf.urls import url

app_name = 'product'

urlpatterns = [
    path('', products, name='index'),
    path('<int:num>', product_byid, name='id'),
    path('add/', addToCart, name='add'),
    path('tbhkrg/', tambahKurangCart, name='tbhkrg'),
    path('grabtotal/', grabTotal, name='grabtotal')
]

review/urls.py
from django.urls import path
from .views import reviews

app_name = 'review'

urlpatterns = [
    path('', reviews, name="review"),
]

shopepew/urls.py
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import path, include
from loginlogout.views import register

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('homepage.urls',  namespace='home')),
    path('register/', register, name='register'),
    path('login/', auth_views.LoginView.as_view(template_name='loginlogout/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(template_name='loginlogout/logout.html'), name='logout'),
    path('payment/', include('payment.urls', namespace='payment'), name='payment'),
    path('product/', include('products.urls', namespace='product'), name='product'),
    path('review/', include('review.urls', namespace='review')),
    path('discount/', include('discount.urls', namespace='discount'), name='discount'),
]

homepage/models.py
from django.db import models

# Create your models here.

homepage/views.py
from django.shortcuts import render
from discount.models import listDiscount
from products.models import Product

def index(request):
    promos = listDiscount.objects.all()[:3]
    products = Product.objects.all()[:6]
    context = {
        'home':'yes',
        'promos': promos,
        'items': products
    }
    return render(request, 'homepage/index.html', context)

homepage/templates/homepage/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>{% block title %} {% endblock %}</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css">
    <link rel="stylesheet" href="{% static 'homepage/navbar.css' %}">
    <link rel="stylesheet" href="{% static 'homepage/main.css' %}">
    <link href="https://fonts.googleapis.com/css?family=Poppins&display=swap" rel="stylesheet">
    <link rel="icon" href="{% static 'homepage/logo black 1.png' %}">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.14.0/css/all.css" integrity="sha384-HzLeBuhoNPvSl5KYnjx0BT+WB0QEEqLprO+NBkkk5gbc67FTaL7XIGa2w1L0Xbgc" crossorigin="anonymous">
    
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"></script>
    <script defer src="https://use.fontawesome.com/releases/v5.13.0/js/all.js"></script>
    <script defer src="https://use.fontawesome.com/releases/v5.13.0/js/v4-shims.js"></script>
    {% block script %}{% endblock %}
    
    <style>
        * {
            font-family: 'Poppins';
        }
        .content{
            margin: 0;
        }
        {% block css %} {% endblock %}
    </style>
</head>

<body>
    {% include 'homepage/include/navbar.html' %}
    {% if messages %}
        {% for message in messages %}
            <div class="alert alert-{{ message.tags }}">{{ message }}</div>
        {% endfor %}
    {% endif %}
    <div class="content">
    {% block body %}

    {% endblock %}
    </div>
</body>

</html>

homepage/templates/homepage/index.html
{% extends 'homepage/base.html' %}
{% load static %}

{% block css %}
#index {
    background: url("{% static 'homepage/bg.jpg' %}") #560526;
    background-size:cover;
    background-blend-mode: multiply;
}
.landing {
    display: block;
    top: 300px;
}
.logo {
    font-size: 6.5rem;
    color: white;
    margin: 1rem;
}
.deals {
    background: rgba(197,111,146,0.4);
    color: #4E1A5C;
}

#products {
    background-color: #370741;
}
{% endblock %}

{% block body %}
<!------------------ LANDING -------------------->

    <div id="index" class="container-fluid d-flex align-items-center justify-content-center">
        <div class="landing d-flex flex-column">
            <!-- <img src="{% static 'homepage/logo white 1.png' %}" class="img-fluid align-self-center" width="100px"> -->
            <i class="fas fa-shopping-bag align-self-center logo"></i>
            <h1 style="color: white;">Beli Semua di Shopepew</h1>
            <div class=" text-center">
                <form method="POST", action="{% url 'product:index' %}">
                    {% csrf_token %}
                    <div class="form-group row justify-content-center">
                        <div class="w-75">
                            <input class="form-control" type="search" placeholder="" aria-label="Search" name="product_name">
                        </div>
                        <button class="btn btn-custom ml-1 my-2 my-sm-0" type="submit">Search</button>
                    </div>
                </form>
                <a href="{% url 'product:index' %}"><button class="btn btn-primary btn-lg my-2 my-sm-0">Shop Now</button></a>
            </div>
        </div>
    </div>

<!------------------ TODAY'S DEALS -------------------->
<div id="deals" class="container-fluid">
    <div class="row ">
        <h2 class="col-12 text-center my-4 py-3 deals">Today's Deals</h2>
    </div>

    <div class="container py-4">
        <div class="row d-flex justify-content-around">
            {% for promo in promos %}
                <div class="col-lg-4 col-sm-6 p-0">
                    <div class="card m-2">
                        <div class="card-header" style="background: url({% cycle 'https://images.unsplash.com/photo-1524721696987-b9527df9e512?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=700&q=60' 'https://images.unsplash.com/photo-1509114397022-ed747cca3f65?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=700&q=60' 'https://images.unsplash.com/photo-1549241520-425e3dfc01cb?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=700&q=60' %}) {% cycle 'indigo' 'palevioletred' 'rebeccapurple' %}; background-blend-mode: luminosity;">
                            <div style="width: 100%; height: 200px;"></div>                
                        </div>
                        <div class="card-body d-flex justify-content-between align-items-center">
                            <span class="">{{ promo.name }}</span>                        
                            <a class="btn btn-primary ml-1" href="{% url 'discount:discount' %}">Use</a>
                        </div>
                    </div>
                </div>
            {% endfor %}
            </div>           
        </div>
        <div class="row justify-content-center"> 
            <a href="{% url 'product:index' %}">
                <button class="btn btn-outline-secondary my-2 mb-4" style="width: 10rem;">See All</button>
            </a>
        </div>
    </div>
</div>
<!------------------ PRODUCTS -------------------->
<div id="products" class="container-fluid pb-5">
    <div class="row">
        <h2 class="col-12 text-center my-4" style="color: white;">Featured Products</h2>
    </div>

    
    <div class="row d-flex flex-wrap justify-content-between m-4">
        {% for item in items %}
            <div class="col-lg-4 col-sm-6 my-3">
                <div class="card">
                    <img src="{{item.imglink}}" class="card-image-top img-fluid" style="width: 100%;">
                    <div class="card-body">
                        <a href="{% url 'product:id' item.id %}">
                            <h5 class="card-title">{{item.name}}</h5>
                        </a>
                    </div>
                    <div class="card-footer">
                        <span class="float-left">
                            {% if user.is_authenticated %}
                            <a href="{% url 'payment:checkout' user.id %}"><button class="btn btn-primary my-2 addToCart ">Buy Now</button></a>
                            {% else %}
                            <a href="{% url 'login' %}"><button class="btn btn-primary my-2">Buy Now</button></a>
                            {% endif %}                            <div product="{{ item.id }}" class="addToCart btn btn-secondary"><i class="fas fa-cart-plus"></i></div>
                        </span>
                        <h5 class="card-text float-right">${{item.price}}</h5>
                    </div>
                </div>
            </div>
        {% endfor %}
    </div>    
    <div class="row justify-content-center">
        <a href="{% url 'product:index' %}">
            <button class="btn btn-outline-secondary my-2 my-sm-0" style="width: 10rem;">See All</button>
        </a>
    </div>
</div>
<!-- notification -->
<div id="notif" style="position: fixed; right: 1rem; top: 4.5rem;">        
</div>
{% endblock %}

{% block script %}
<script>$(document).ready(function() {
function notif(imgLink, name, price) {           
    $("#notif").append('<div class="alert alert-success"><img src="' + imgLink + '" alt="" class="mr-2" style="height: 75px; width: auto; border-radius: 5px;"><span class="float-right">' + name + '<br>$' + price + '<br><b>Added to cart!</b></span></div>'); 
    $("#notif").css("opacity", "1");    
    $("#notif").css("transition", "all .5s ease");   
    setTimeout(function() {            
        $("#notif").css("opacity", "0");            
    }, 2500);
    setTimeout(function() {
        $("#notif").empty();            
    }, 3000);
            
}

$(".addToCart").click(function(){
    var product = $(this).attr("product");
    console.log(product)
    $.ajax({
        url: "{% url 'product:add' %}", 
        data: { user: "{{ user.username }}", product: product },

        success: function(product) {
            console.log(product);
            notif(product.imglink, product.name, product.price);                    
        },

        type: 'POST'
    });
});

});</script>
{% endblock %}