homepage/urls.py
from django.urls import path
from .views import index

app_name = 'homepage'

urlpatterns = [
    path('', index, name='index'),
]

payment/urls.py
from django.urls import path
from .views import checkout, invoice, useCoupon

app_name = 'payment'

urlpatterns = [
    path('<int:id>', checkout, name="checkout"),
    path('invoice/<int:id>', invoice, name="invoice"),
    path('useCoupon', useCoupon, name="useCoupon"),
]

review/urls.py
from django.urls import path
from .views import reviews

app_name = 'review'

urlpatterns = [
    path('', reviews, name="review"),
]

shopepew/urls.py
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import path, include
from loginlogout.views import register

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('homepage.urls',  namespace='home')),
    path('register/', register, name='register'),
    path('login/', auth_views.LoginView.as_view(template_name='loginlogout/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(template_name='loginlogout/logout.html'), name='logout'),
    path('payment/', include('payment.urls', namespace='payment'), name='payment'),
    path('product/', include('products.urls', namespace='product'), name='product'),
    path('review/', include('review.urls', namespace='review')),
    path('discount/', include('discount.urls', namespace='discount'), name='discount'),
]

homepage/models.py
from django.db import models

# Create your models here.

homepage/views.py
from django.shortcuts import render
from discount.models import listDiscount
from products.models import Product

def index(request):
    promos = listDiscount.objects.all()[:3]
    products = Product.objects.all()[:6]
    context = {
        'home':'yes',
        'promos': promos,
        'items': products
    }
    return render(request, 'homepage/index.html', context)

homepage/templates/homepage/include/navbar.html
{% load static %}
<nav class="navbar navbar-adjust navbar-expand-lg navbar-dark fixed-top" style="background-color: #4e1a5c!important;">
    
    <a class="navbar-brand d-flex align-items-center" href="{% url 'home:index' %}">
      <!-- <img class="navbar-logo" src="{% static 'homepage/navbar-logo.svg' %}"> -->
      <i class="fas fa-shopping-bag navbar-logo mr-2"></i> Shopepew
    </a>

    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
        {% if home == 'yes' %}
        {% else %}
        <form class="form-inline my-2 my-sm" method="POST", action="{% url 'product:index' %}">
            {% csrf_token %}
            <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search" name="product_name">
        </form>
        {% endif %}
        <ul class="navbar-nav mr-auto">
        </ul>
        <a class="nav-custom" href="{% url 'home:index' %}">Home</a>
        <br>
        <a class="nav-custom" href="{% url 'discount:discount' %}">Promos</a>
        <br>
        <a href="{% url 'product:index' %}"><button class="btn btn-primary my-2">Shop</button></a>
        {% if user.is_authenticated %}
          <a class="nav-custom" href="{% url 'payment:checkout' user.id %}">
            <i class="fas fa-shopping-cart"></i>
          </a>
          <br>
          <a class="nav-custom" href="{% url 'logout' %}">Logout</a>
        {% else %}
          <br>
          <a class="nav-custom" href="{% url 'login' %}">Login</a>
          <br>
          <a class="nav-custom" href="{% url 'register' %}">Register</a>
        {% endif %}
   </div>
</nav>